Game::ExecutionBlock::Executor1 executor1;
executor1.loadContext();
executor1.initiate();
Game::ExecutionBlock::Executor2 executor2;
executor2.loadContext();
executor2.initiate();
Game::ExecutionBlock::Executor3 executor3;
executor3.loadContext();
executor3.pool1Context = &poolInst1Context;
executor3.initiate();
Game::ExecutionBlock::Executor4 executor4;
executor4.loadContext();
executor4.pool2Context = &poolInst2Context;
executor4.pool3Context = &poolInst3Context;
executor4.initiate();
Game::ExecutionBlock::Executor5 executor5;
executor5.loadContext();
executor5.pool2Context = &poolInst2Context;
executor5.pool3Context = &poolInst3Context;
executor5.initiate();
Game::ExecutionBlock::Executor6 executor6;
executor6.loadContext();
executor6.pool3Context = &poolInst3Context;
executor6.initiate();
