Game::Context::SContext1::Data sharedInst1Context;
Game::Context::SContext1::Data sharedInst2Context;
Game::Context::SContext2::Data sharedInst3Context;
Game::Context::SContext2::Data sharedInst4Context;
Game::Context::SContext3::Data sharedInst5Context;
sharedInst1Context.load();
sharedInst2Context.load();
sharedInst3Context.load();
sharedInst4Context.load();
sharedInst5Context.load();
